// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package SC2APIProtocol is a generated protocol buffer package.

It is generated from these files:
	common.proto
	data.proto
	debug.proto
	error.proto
	query.proto
	raw.proto
	sc2api.proto
	score.proto
	spatial.proto
	ui.proto

It has these top-level messages:
	AvailableAbility
	ImageData
	PointI
	RectangleI
	Point2D
	Point
	Size2DI
	AbilityData
	DamageBonus
	Weapon
	UnitTypeData
	UpgradeData
	BuffData
	DebugCommand
	DebugDraw
	Line
	Color
	DebugText
	DebugLine
	DebugBox
	DebugSphere
	DebugCreateUnit
	DebugKillUnit
	DebugTestProcess
	DebugSetScore
	DebugEndGame
	DebugSetUnitValue
	DebugChat
	RequestQuery
	ResponseQuery
	RequestQueryPathing
	ResponseQueryPathing
	RequestQueryAvailableAbilities
	ResponseQueryAvailableAbilities
	RequestQueryBuildingPlacement
	ResponseQueryBuildingPlacement
	StartRaw
	ObservationRaw
	PowerSource
	PlayerRaw
	UnitOrder
	PassengerUnit
	Unit
	MapState
	ActionRaw
	ActionRawUnitCommand
	ActionRawCameraMove
	ActionRawToggleAutocast
	Event
	Request
	Response
	RequestCreateGame
	LocalMap
	ResponseCreateGame
	RequestJoinGame
	PortSet
	ResponseJoinGame
	RequestRestartGame
	ResponseRestartGame
	RequestStartReplay
	ResponseStartReplay
	RequestLeaveGame
	ResponseLeaveGame
	RequestQuickSave
	ResponseQuickSave
	RequestQuickLoad
	ResponseQuickLoad
	RequestQuit
	ResponseQuit
	RequestGameInfo
	ResponseGameInfo
	RequestObservation
	ResponseObservation
	ChatReceived
	RequestAction
	ResponseAction
	RequestStep
	ResponseStep
	RequestData
	ResponseData
	RequestSaveReplay
	ResponseSaveReplay
	RequestReplayInfo
	PlayerInfoExtra
	ResponseReplayInfo
	RequestAvailableMaps
	ResponseAvailableMaps
	RequestSaveMap
	ResponseSaveMap
	RequestPing
	ResponsePing
	RequestDebug
	ResponseDebug
	PlayerSetup
	SpatialCameraSetup
	InterfaceOptions
	PlayerInfo
	PlayerCommon
	Observation
	Action
	ActionChat
	ActionError
	PlayerResult
	Score
	CategoryScoreDetails
	VitalScoreDetails
	ScoreDetails
	ObservationFeatureLayer
	FeatureLayers
	FeatureLayersMinimap
	ObservationRender
	ActionSpatial
	ActionSpatialUnitCommand
	ActionSpatialCameraMove
	ActionSpatialUnitSelectionPoint
	ActionSpatialUnitSelectionRect
	ObservationUI
	ControlGroup
	UnitInfo
	SinglePanel
	MultiPanel
	CargoPanel
	ProductionPanel
	ActionUI
	ActionControlGroup
	ActionSelectArmy
	ActionSelectWarpGates
	ActionSelectLarva
	ActionSelectIdleWorker
	ActionMultiPanel
	ActionCargoPanelUnload
	ActionProductionPanelRemoveFromQueue
	ActionToggleAutocast
*/
package SC2APIProtocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AvailableAbility struct {
	AbilityId        *int32 `protobuf:"varint,1,opt,name=ability_id,json=abilityId" json:"ability_id,omitempty"`
	RequiresPoint    *bool  `protobuf:"varint,2,opt,name=requires_point,json=requiresPoint" json:"requires_point,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AvailableAbility) Reset()                    { *m = AvailableAbility{} }
func (m *AvailableAbility) String() string            { return proto.CompactTextString(m) }
func (*AvailableAbility) ProtoMessage()               {}
func (*AvailableAbility) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AvailableAbility) GetAbilityId() int32 {
	if m != nil && m.AbilityId != nil {
		return *m.AbilityId
	}
	return 0
}

func (m *AvailableAbility) GetRequiresPoint() bool {
	if m != nil && m.RequiresPoint != nil {
		return *m.RequiresPoint
	}
	return false
}

type ImageData struct {
	BitsPerPixel     *int32   `protobuf:"varint,1,opt,name=bits_per_pixel,json=bitsPerPixel" json:"bits_per_pixel,omitempty"`
	Size             *Size2DI `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	Data             []byte   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ImageData) Reset()                    { *m = ImageData{} }
func (m *ImageData) String() string            { return proto.CompactTextString(m) }
func (*ImageData) ProtoMessage()               {}
func (*ImageData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ImageData) GetBitsPerPixel() int32 {
	if m != nil && m.BitsPerPixel != nil {
		return *m.BitsPerPixel
	}
	return 0
}

func (m *ImageData) GetSize() *Size2DI {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *ImageData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Point on the screen/minimap (e.g., 0..64).
// Note: bottom left of the screen is 0, 0.
type PointI struct {
	X                *int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PointI) Reset()                    { *m = PointI{} }
func (m *PointI) String() string            { return proto.CompactTextString(m) }
func (*PointI) ProtoMessage()               {}
func (*PointI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PointI) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PointI) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

// Screen space rectangular area.
type RectangleI struct {
	P0               *PointI `protobuf:"bytes,1,opt,name=p0" json:"p0,omitempty"`
	P1               *PointI `protobuf:"bytes,2,opt,name=p1" json:"p1,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RectangleI) Reset()                    { *m = RectangleI{} }
func (m *RectangleI) String() string            { return proto.CompactTextString(m) }
func (*RectangleI) ProtoMessage()               {}
func (*RectangleI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RectangleI) GetP0() *PointI {
	if m != nil {
		return m.P0
	}
	return nil
}

func (m *RectangleI) GetP1() *PointI {
	if m != nil {
		return m.P1
	}
	return nil
}

// Point on the game board, 0..255.
// Note: bottom left of the screen is 0, 0.
type Point2D struct {
	X                *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Point2D) Reset()                    { *m = Point2D{} }
func (m *Point2D) String() string            { return proto.CompactTextString(m) }
func (*Point2D) ProtoMessage()               {}
func (*Point2D) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Point2D) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Point2D) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

// Point on the game board, 0..255.
// Note: bottom left of the screen is 0, 0.
type Point struct {
	X                *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Point) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Point) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

// Screen dimensions.
type Size2DI struct {
	X                *int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Size2DI) Reset()                    { *m = Size2DI{} }
func (m *Size2DI) String() string            { return proto.CompactTextString(m) }
func (*Size2DI) ProtoMessage()               {}
func (*Size2DI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Size2DI) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Size2DI) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*AvailableAbility)(nil), "SC2APIProtocol.AvailableAbility")
	proto.RegisterType((*ImageData)(nil), "SC2APIProtocol.ImageData")
	proto.RegisterType((*PointI)(nil), "SC2APIProtocol.PointI")
	proto.RegisterType((*RectangleI)(nil), "SC2APIProtocol.RectangleI")
	proto.RegisterType((*Point2D)(nil), "SC2APIProtocol.Point2D")
	proto.RegisterType((*Point)(nil), "SC2APIProtocol.Point")
	proto.RegisterType((*Size2DI)(nil), "SC2APIProtocol.Size2DI")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x49, 0xdc, 0xd4, 0xfd, 0x57, 0x87, 0xe4, 0xa0, 0xbb, 0x08, 0xa3, 0x6c, 0x32, 0x10,
	0xc6, 0xd6, 0x6f, 0x30, 0xdc, 0x25, 0xb7, 0x92, 0x5d, 0x3c, 0x08, 0x25, 0x6b, 0xc3, 0x08, 0xa4,
	0x4d, 0x4c, 0xa3, 0xb4, 0xfd, 0xf4, 0x92, 0xac, 0x22, 0x13, 0xdc, 0x2d, 0xef, 0xf1, 0xe3, 0xbd,
	0xf7, 0x0f, 0x44, 0xb9, 0x2e, 0x4b, 0x5d, 0xad, 0x8c, 0xd5, 0x4e, 0x93, 0xc9, 0xfe, 0x35, 0xd9,
	0xa6, 0x34, 0xf5, 0x22, 0xd7, 0x2a, 0x7e, 0x83, 0xfb, 0xed, 0x17, 0x97, 0x8a, 0x1f, 0x94, 0xd8,
	0x1e, 0xa4, 0x92, 0xae, 0x25, 0x4f, 0x00, 0xfc, 0xf4, 0xcc, 0x64, 0x31, 0x45, 0x33, 0xb4, 0x1c,
	0xb2, 0x51, 0xef, 0xd0, 0x82, 0x2c, 0x60, 0x62, 0xc5, 0xc7, 0xa7, 0xb4, 0xa2, 0xce, 0x8c, 0x96,
	0x95, 0x9b, 0xe2, 0x19, 0x5a, 0xde, 0xb2, 0xbb, 0x1f, 0x37, 0xf5, 0x66, 0x6c, 0x61, 0x44, 0x4b,
	0x7e, 0x14, 0x3b, 0xee, 0x38, 0x99, 0xc3, 0xe4, 0x20, 0x5d, 0x9d, 0x19, 0x61, 0x33, 0x23, 0x1b,
	0xa1, 0xfa, 0xd8, 0xc8, 0xbb, 0xa9, 0xb0, 0xa9, 0xf7, 0xc8, 0x0b, 0x0c, 0x6a, 0xd9, 0x89, 0x90,
	0x37, 0x4e, 0x1e, 0x57, 0xe7, 0x5b, 0x57, 0x7b, 0xd9, 0x89, 0x64, 0x47, 0x59, 0x80, 0x08, 0x81,
	0x41, 0xc1, 0x1d, 0x9f, 0x5e, 0xcd, 0xd0, 0x32, 0x62, 0xe1, 0x1d, 0xcf, 0xe1, 0x3a, 0x94, 0x53,
	0x12, 0x01, 0x6a, 0xfa, 0x0e, 0xd4, 0x78, 0xd5, 0x86, 0xd4, 0x21, 0x43, 0x6d, 0xfc, 0x0e, 0xc0,
	0x44, 0xee, 0x78, 0x75, 0x54, 0x82, 0x92, 0x67, 0xc0, 0x66, 0x1d, 0xd0, 0x71, 0xf2, 0xf0, 0xb7,
	0xf2, 0x94, 0xc6, 0xb0, 0x59, 0x07, 0x6e, 0xd3, 0x4f, 0xfb, 0x9f, 0xdb, 0xc4, 0x0b, 0xb8, 0x09,
	0x2a, 0xd9, 0xfd, 0x8e, 0xc0, 0x67, 0x23, 0xb0, 0x1f, 0xb1, 0x81, 0x61, 0xc0, 0x2e, 0x41, 0x5e,
	0x75, 0xe1, 0x40, 0xcc, 0x50, 0xe7, 0x93, 0xfb, 0x2f, 0xb8, 0x74, 0xde, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x29, 0x4d, 0x58, 0xf1, 0x01, 0x00, 0x00,
}
